### ISSUE TITLE
Set up a Kanban board

### ISSUE THREAD

**Issue by ankitt26** [ankitt26/Catalog-of-my-things#30]
### "We are a team of 3 people working on this project."

- The group task is assigned to - _@ankitt26_,  _@forLoop94 , @toyman640_ 
- Student A - _@ankitt26_ 
- student B - _@forLoop94_ 
- Student C - _@toyman640_ 

**Link of the project -**: https://github.com/ankitt26/Catalog-of-my-things/projects/1

**Comment by KayLemba** [comment]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @TEAM     , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  . 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Kanban setup correctly 🥇  



 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Comment by ankitt26** [comment]
Thanks for Approving 😊🎊
